

build:
	npx electron-builder build --mac

open:
	cd /opt/goinfre/hjerilyn/projects/python_calc_3/git_rep_python_calc/electron_test/dist/mac/electron_test.app/Contents/MacOS/ ; ./electron_test

clean:
	rm -rf dist/

rebuild: clean build open
